version: "3.9"

services:
  maquina17:
    container_name: maquina17
    build:
      context: .
      dockerfile: Dockerfile
  maquina18:
    container_name: maquina18
    build:
      context: .
      dockerfile: Dockerfile
  maquina19:
    container_name: maquina19
    build:
      context: .
      dockerfile: Dockerfile
  maquina20:
    container_name: maquina20
    build:
      context: .
      dockerfile: Dockerfile